version: '3.8'

services:
  mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - .:/app